# You can use this file to create a conda environment for this pipeline:
#   conda env create -f environment.yml
name: ramdaq-2.0dev
channels:
  - conda-forge
  - bioconda
dependencies:
  - conda-forge::libcurl
  - conda-forge::readline=8.2
  - conda-forge::python=3.10
  - conda-forge::r-base
  - conda-forge::r-data.table
  - conda-forge::r-gplots
  - conda-forge::r-markdown
  - conda-forge::r-stringr
  - conda-forge::r-ggplot2
  - conda-forge::r-dplyr
  - conda-forge::r-rtsne
  - conda-forge::r-umap
  - conda-forge::markdown=3.1.1
  - conda-forge::pymdown-extensions=6.0
  - conda-forge::pygments=2.5.2

  - bioconductor-edger=4.0.16
  - bioconda::fastqc=0.12.1
  - bioconda::multiqc=1.9
  - bioconda::hisat2=2.2.1
  - bioconda::qualimap=2.3
  - bioconda::rseqc=5.0.3
  - bioconda::ea-utils=1.1.2.779
  - bioconda::samtools=1.20
  - bioconda::ucsc-wigtobigwig=447
  - bioconda::bamtools=2.5.2
  - bioconda::subread=2.0.6
  - bioconda::rsem=1.3.3
  - bioconda::bowtie2=2.5.4
